config/routes.rb
Rails.application.routes.draw do
  devise_for :users

	devise_scope :user do
	  authenticated :user do
	    root 'todo_lists#index', as: :authenticated_root
	  end

	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end

	resources :user, only: [] do
		resources :todo_lists, only: [:index, :show] do
			resources :todo_items, only: [:index, :show]
		end
	end

	resources :todo_lists do 
		resources :todo_items
	end

	resources :todo_items
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
	belongs_to :user
	belongs_to :todo_list
	validates :task_name, presence: true
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
	belongs_to :user
	has_many :todo_items, dependent: :destroy
	validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :todo_lists
  has_many :todo_items, through: :todo_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  def index
    if params[:todo_list_id]
      @todo_list = TodoList.find_by(id: params[:todo_list_id])
      @todo_items = @todo_list.todo_items.page(params[:page]).per(params[:per])
    else
      @todo_items = current_user.todo_items.page(params[:page]).per(params[:per])
    end
  end

  def show
  end

  def new
    @todo_item = TodoList.find_by(id: params[:todo_list_id]).todo_items.new
  end

  def edit
  end

  def create
    @todo_item = TodoItem.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { render :show }
        format.js { render :create }
      else
        format.html { render :new }
      end
    end
  end
  # format.html { redirect_to "/todo_lists/#{@todo_item.todo_list_id}" }

  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_items }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to :back }
    end
  end

  private
    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    def todo_item_params
      params.require(:todo_item).permit(:todo_list_id, :task_name, :description, :due_date, :complete)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  def index
    if params[:user_id]
      @user = User.find_by(id: params[:user_id])
      @todo_lists = @user.todo_lists.page(params[:page]).per(params[:per])
    else
      @todo_lists = current_user.todo_lists.page(params[:page]).per(params[:per])
    end
  end

  def show
    @todo_items = TodoList.find_by(id: params[:id]).todo_items
  end

  def new
    @todo_list = current_user.todo_lists.new
  end

  def edit
  end

  def create
    @todo_list = current_user.todo_lists.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to "/todo_lists"}
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url }
    end
  end

  private
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    def todo_list_params
      params.require(:todo_list).permit(:user_id, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Justdodat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="/">JustDoDat</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Account Settings", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <% end %>
          <% if !current_user %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  
  <div class="container">
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>

</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for(@todo_item) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :todo_list_id %><br>
    <%= f.number_field :todo_list_id %>
  </div>
  <div class="field">
    <%= f.label :task_name %><br>
    <%= f.text_field :task_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_items/_item.html.erb
<tr>
  <td>
    <% if todo_item.complete %>
      <%= button_to '', todo_item, method: :put, class: "glyphicon glyphicon-check", 
        form: { todo_item: { todo_list_id: params[:id], complete: false } }  %>
    <% else %>
      <%= button_to '', todo_item, method: :put, class: "glyphicon glyphicon-unchecked", form: { todo_item: { todo_list_id: params[:id], complete: true } } %>
    <% end %>
  </td>
  <td><%= todo_item.task_name %></td>
  <td><%= link_to '', todo_item, method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-remove pull-right", todo_list_id: params[:id] %></td>
</tr>

app/views/todo_items/_newform.html.erb
<%= form_for TodoItem.new, remote: true do |f| %>
  <div class="form-group">
    <div class="row">
      <div class="col-xs-12">
        <%= f.text_field :task_name, placeholder: "Enter New Task Name Here...", class: "form-control" %>
        <%= f.hidden_field :todo_list_id, value: params[:id] %>
      </div>
    </div>
  </div>
<% end %>

app/views/todo_items/create.js.erb
<% new_task = render partial: "item", locals: { todo_item: @todo_item } %>
$(".todo-list-items").append("<%= escape_javascript(new_task) %>")

$(".todo-item-form").replaceWith("<%= j(render partial: "todo_items/newform") %>")

app/views/todo_items/edit.html.erb
<h1>Editing Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_item %> |
<%= link_to 'Back', todo_items_path %>

app/views/todo_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todo Items</h1>

<table>
  <thead>
    <tr>
      <th>Todo list</th>
      <th>Task name</th>
      <th>Description</th>
      <th>Due date</th>
      <th>Complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_items.each do |todo_item| %>
      <tr>
        <td><%= todo_item.todo_list_id %></td>
        <td><%= todo_item.task_name %></td>
        <td><%= todo_item.description %></td>
        <td><%= todo_item.due_date %></td>
        <td><%= todo_item.complete %></td>
        <td><%= link_to 'Show', todo_item %></td>
        <td><%= link_to 'Edit', edit_todo_item_path(todo_item) %></td>
        <td><%= link_to 'Destroy', todo_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo item', new_todo_item_path %>

app/views/todo_items/new.html.erb
<h1>New Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_items_path %>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Todo list:</strong>
  <%= @todo_item.todo_list_id %>
</p>

<p>
  <strong>Task name:</strong>
  <%= @todo_item.task_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_item.description %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @todo_item.due_date %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @todo_item.complete %>
</p>

<%= link_to 'Edit', edit_todo_item_path(@todo_item) %> |
<%= link_to 'Back', todo_items_path %>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->


<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="todo-list-index">
      <h1 style="margin-top: 10px;">Todo Lists</h1>
        <%= form_for TodoList.new do |f| %>
          <div class="form-group">
            <div class="row">
              <div class="col-xs-12">
                <%= f.text_field :title, placeholder: "Enter New List Name Here...", class: "form-control" %>
              </div>
            </div>
          </div>
        <% end %>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Title:</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody class="todo-list-items">
          <% @todo_lists.each do |todo_list| %>
            <tr>
              <td><%= todo_list.title %></td>
              <td><%= link_to 'Show', todo_list, class: "btn btn-default btn-xs" %></td>
              <td><%= link_to 'Edit', edit_todo_list_path(todo_list), class: "btn btn-default btn-xs" %></td>
              <td><%= link_to 'Delete', todo_list, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <!-- <%= link_to 'New Todo list', new_todo_list_path %> -->
  </div>
</div>


<!-- , nil, placeholder: "Enter New List Name Here...", class: "form-control" -->

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<!-- <p id="notice"><%= notice %></p>
 -->
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="todo-list-show">
      <h1><%= @todo_list.title %></h1>
        <div class="todo-item-form">
          <%= render partial: 'todo_items/newform', locals: { params: params } %>
        </div>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Task Name:</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody class="todo-list-items">
            <% @todo_items.each do |todo_item| %>
              <tr>
                <td>
                  <% if todo_item.complete %>
                    <%= link_to '', todo_item, method: :put, class: "glyphicon glyphicon-check", 
                      form: { todo_item: { todo_list_id: params[:id], complete: false } }  %>
                  <% else %>
                    <%= link_to '', todo_item, method: :put, class: "glyphicon glyphicon-unchecked", form: { todo_item: { todo_list_id: params[:id], complete: true } } %>
                  <% end %>
                </td>
                <td><%= todo_item.task_name %></td>
                <td><%= link_to '', todo_item, method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-remove pull-right", todo_list_id: params[:id] %></td>
              </tr>
            <% end %>
          </tbody>
        </table>


      <!-- <%= link_to 'Add New Task', new_todo_item_path(todo_list_id: params[:id]) %> -->
      <div class="text-right">
        <%= link_to 'Edit', edit_todo_list_path(@todo_list), class: "btn btn-default btn-xs" %> 
        <%= link_to 'Back', todo_lists_path, class: "btn btn-default btn-xs" %>
      </div>
    </div>
  </div>
</div>